#Generated by Fabric Compiler ( version 2022.1 <build 99559> ) at Mon May 15 23:18:41 2023

add_design "C:/Users/wkk/Desktop/program/program/source/top.v"
add_design C:/Users/wkk/Desktop/program/program/ipcore/sys_pll/sys_pll.idf
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi/iic_dri.v"
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi/ms72xx_ctl.v"
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi/ms7200_ctl.v"
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi/ms7210_ctl.v"
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi/sync_vg.v"
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi_top.v"
add_constraint "C:/Users/wkk/Desktop/program/program/source/hdmi/constr/hdmi_loop.fdc"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module hdmi_top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
add_design "C:/Users/wkk/Desktop/program/program/source/hdmi/pattern_vg.v"
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
set_arch -family Logos -device PGL50H -speedgrade -6 -package FBG484
synthesize -synplify_pro -selected_syn_tool_opt 1 -top_module top
dev_map 
pnr 
report_timing 
gen_bit_stream 
